project:
  type: book

book:
  title: "Capstone"
  downloads: [pdf]
  author: "Team"
  date: today
  chapters:
    - index.qmd
    - chapters/github.qmd
    - chapters/proposal.qmd
    - chapters/test_python.qmd
    - section: "Individual Downloads"
        contents:
          - text: "Browse Chapter PDFs"
            href: standalone-pdfs/
            icon: file-pdf
    
  site-url: https://adyadyan.github.io/MAP-5629-Capstone/
  repo-url: https://github.com/adyadyan/MAP-5629-Capstone
  repo-actions: [edit, source, issue]
  search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Chapters"
        contents:
          - index.qmd
          - chapters/github.qmd
          - chapters/proposal.qmd
          - chapters/test_python.qmd
      - section: "Downloads"
        contents:
          - text: "Individual Chapter PDFs"
            href: standalone-pdfs/
    
format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    toc-depth: 2
    
execute:
  freeze: auto  # 'auto' only re-runs if the source file has changed