project:
  type: book

book:
  title: "Capstone"
  author: "Team"
  date: today
  downloads: [pdf]
  navbar:
    right:
      - text: "📊 Live Dashboard"
        href: my-dashboard.qmd
  chapters:
    - index.qmd
    - chapters/proposal.qmd
  appendices:
    - chapters/downloads.qmd
    - chapters/github.qmd
    - chapters/test_python.qmd
    - chapters/ipynb_part1.qmd

  site-url: https://adyadyan.github.io/MAP-5629-Capstone/
  repo-url: https://github.com/adyadyan/MAP-5629-Capstone
  repo-actions: [edit, source, issue]

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    toc-depth: 2

execute:
  freeze: auto
