<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Md Tanvir Hossain">
<meta name="author" content="Veronica Prelaz">
<meta name="author" content="Adyan Rios">
<meta name="dcterms.date" content="2026-04-24">

<title>2&nbsp; Fisher Rainy Day Fund – A Parametric Insurance Policy – Capstone</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/downloads.html" rel="next">
<link href="../chapters/proposal.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="../site_libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Capstone</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../fdi_dashboard.html"> 
<span class="menu-text">📊 Live Dashboard</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/adyadyan/MAP-5629-Capstone" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Capstone.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/capstone.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fisher Rainy Day Fund – A Parametric Insurance Policy</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/proposal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Proposal</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/capstone.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fisher Rainy Day Fund – A Parametric Insurance Policy</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/downloads.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Downloads</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/github.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">GitHub Setup</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/test_python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Test Python</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ipynb_part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Python Notebook Part 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/poisson_binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">poisson_binomial</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#fisher-rainy-day-fund-a-parametric-insurance-policy" id="toc-fisher-rainy-day-fund-a-parametric-insurance-policy" class="nav-link active" data-scroll-target="#fisher-rainy-day-fund-a-parametric-insurance-policy">Fisher Rainy Day Fund – A Parametric Insurance Policy</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2.1</span> Introduction</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">2.2</span> Background</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">2.3</span> Methods</a>
  <ul class="collapse">
  <li><a href="#sources-of-data" id="toc-sources-of-data" class="nav-link" data-scroll-target="#sources-of-data"><span class="header-section-number">2.3.1</span> Sources of Data</a></li>
  <li><a href="#methodology-for-pricing-the-weather-derivative" id="toc-methodology-for-pricing-the-weather-derivative" class="nav-link" data-scroll-target="#methodology-for-pricing-the-weather-derivative"><span class="header-section-number">2.3.2</span> Methodology for Pricing the Weather Derivative</a></li>
  <li><a href="#poisson-binomial-model" id="toc-poisson-binomial-model" class="nav-link" data-scroll-target="#poisson-binomial-model"><span class="header-section-number">2.3.3</span> Poisson-Binomial Model</a></li>
  <li><a href="#limiting-probability-equation" id="toc-limiting-probability-equation" class="nav-link" data-scroll-target="#limiting-probability-equation"><span class="header-section-number">2.3.4</span> Limiting Probability Equation</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">2.4</span> Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">2.5</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">2.6</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/adyadyan/MAP-5629-Capstone/edit/main/chapters/capstone.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/adyadyan/MAP-5629-Capstone/blob/main/chapters/capstone.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/adyadyan/MAP-5629-Capstone/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fisher Rainy Day Fund – A Parametric Insurance Policy</span></h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Md Tanvir Hossain </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Veronica Prelaz </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Florida International University
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Adyan Rios </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Florida International University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>MAP 5629: Quantitative Capstone in Environmental Finance<br>
    Dr.&nbsp;Pablo Olivares</p>
  </div>
</div>


</header>


<section id="fisher-rainy-day-fund-a-parametric-insurance-policy" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="fisher-rainy-day-fund-a-parametric-insurance-policy">Fisher Rainy Day Fund – A Parametric Insurance Policy</h2>
</section>
<section id="introduction" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">2.1</span> Introduction</h2>
<p>Fishermen are often unable to produce income due to reasons beyond their control. For example, weather and ocean conditions can make it unsafe to go fishing. Additionally, fisheries are sometimes closed deliberately to protect spawning times, ensure sustainable harvest rates, and allow overexploited stocks to replenish. While environmentally necessary, these restrictions diminish short-term fishing opportunities and income. The aim of this project is to create and cost a parametric derivative agreement that provides financial protection when fishing days are lost due to objectively defined negative environmental conditions.</p>
<p>The proposed Fisher Rainy Day Fund is a parametric insurance policy that is based on a Fishable Days Index (FDI). The contract counts the days in a season when fishing is legally permitted and environmentally feasible. This project uses a quantitative framework with three objectives: (1) define the fishable days using wind and wave meteorological conditions, (2) model the stochastic behavior of fishable and unfishable days through a Poisson-binomial distribution, and (3) price an index-based derivative. The system is based on weather derivative pricing but altered slightly to fit the operational realities of a small-scale island-based fisheries.</p>
</section>
<section id="background" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="background"><span class="header-section-number">2.2</span> Background</h2>
<p>Income shocks have a big impact on small fisheries. The performance of traditional indemnity insurance in this sector is not up to the mark as it becomes difficult to verify losses and claims are settled slowly. Furthermore, controlling moral hazard is difficult. For this reason, many fishers are not insured. Parametric and index-based products provide clear and low-cost alternatives, as payouts depend on objective indices rather than observed losses <span class="citation" data-cites="skees2008">(<a href="capstone.html#ref-skees2008" role="doc-biblioref">Skees 2008</a>)</span>.</p>
</section>
<section id="methods" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="methods"><span class="header-section-number">2.3</span> Methods</h2>
<section id="sources-of-data" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="sources-of-data"><span class="header-section-number">2.3.1</span> Sources of Data</h3>
<p>This study integrates four primary datasets to construct and validate the Fishable Days Index (FDI) for the St.&nbsp;Croix commercial fishery that targets Caribbean Spiny Lobster. Each dataset spans a study period from January 1, 1985, to December 28, 2024, resulting in a daily time series of 14,607 observations. All data loading, merging, and transformation were performed with the programming language “Python” to ensure full reproducibility and to avoid manual manipulation of the four source files.</p>
<p>The first dataset consists of daily commercial catch reports from individual fishers <span class="citation" data-cites="caribbea">(<a href="capstone.html#ref-caribbea" role="doc-biblioref">Southeast Fisheries Science Center 2026</a>)</span>. Each observation records information for every fishing trip made by vessels fishing in St.&nbsp;Croix. The important variables utilized for this analysis were the date, total number of trips, number of trips specifically for the Caribbean Spiny Lobster (CSL), and total pounds of all species caught alongside pounds of solely CSL. The dataset is a limited event log: rows are present only on days when at least three fishers filed a self-reported logbook. Days with fewer than three individual reports are suppressed to zero to protect fisher privacy, meaning that missing continuous-date rows represent a mix of truly inactive days and days with only one or two reported trips.</p>
<p>The second and third datasets of wind speed and wave height, respectively, are derived from the ERA5 reanalysis product produced by the European Centre for Medium-Range Weather Forecasts (ECMWF). ERA5 provides hourly estimates of atmospheric and oceanic variables at a grid resolution of 31 km from 1940 onwards, reconstructed from historical observations and numerical weather prediction models <span class="citation" data-cites="hersbach2020">(<a href="capstone.html#ref-hersbach2020" role="doc-biblioref">Hersbach et al. 2020</a>)</span>. The wind dataset provides hourly eastward, u10, and northward, v10, wind components from 10 meters above the surface, as well as the instantaneous wind gust speed, fg10, for a single grid point representative of the St.&nbsp;Croix region (17.75°N, 64.75°W). The wave dataset provides hourly significant wave height, swh, at a nearby grid point (18.0°N, 64.5°W), defined as the average height of the greatest one-third of waves.</p>
<p>The fourth dataset consists of annual total population estimates for the United States Virgin Islands sourced from the World Bank, series POPTOTVIA647NWDB. Population data are used solely to normalize fishing activity metrics and remove secular trends in fleet capacity from the validation analysis, as described further below.</p>
<section id="daily-calendar-framework-construction" class="level4" data-number="2.3.1.1">
<h4 data-number="2.3.1.1" class="anchored" data-anchor-id="daily-calendar-framework-construction"><span class="header-section-number">2.3.1.1</span> Daily Calendar Framework Construction</h4>
<p>A complete daily calendar skeleton was constructed spanning the full study period using pandas date_range functionality, producing a main data frame of explicitly 14,607 rows. The limited fishing report file was left-joined onto this skeleton so that days absent from the original file became explicit rows with zero values for all fishing activity columns rather than structural absences. This distinction is significant: a day with zero reported trips carries different analytical meaning depending on whether it reflects true fishing trip inactivity, privacy-based censoring of low-report days, or adverse weather conditions. The calendar join method makes all three types of zero-day observable within the same framework.</p>
<p>Hourly ERA5 wind data were processed by first computing the scalar wind speed from the u and v vector components as the Euclidean magnitude, expressed formally as <span class="math inline">\(|W| = \sqrt{u_{10}^2 + v_{10}^2}\)</span> with units of meters per second <span class="math inline">\((m/s)\)</span>. Wind speeds were additionally converted to knots using the exact conversion factor of <span class="math inline">\(1 m/s = 1.9438449\)</span> knots. Both scalar wind speed and gust speed were then transformed from hourly to daily frequency by taking the maximum of the daily values. The choice of daily maximum rather than daily mean reflects the operational reality that a single period of dangerous wind or wave conditions within a day is sufficient to prevent fishing activity regardless of conditions during other hours. This process was replicated to transform hourly significant wave heights to daily maximum values.</p>
<p>To isolate climate-driven variation in lobster fishing activity from background trends driven by changes in the island’s population and fishing fleet capacity, all fishing activity metrics used in the threshold validation were normalized by annual population. Specifically, CSL trip rates were expressed as the number of lobster trips per 1,000 residents, and CSL catch rates were expressed as pounds of lobster caught per 1,000 residents per day. This normalization process allows for using the activity rates of fishing rather than raw counts, ensuring that this signal reflects responses to environmental conditions rather than changes driven by population demands.</p>
<p>The four datasets were merged into a single main daily table using calendar date as the primary join factor for climate data and integer year as the join factor for annual population values. Forward-filling was applied to any missing climate values arising from gaps in hourly ERA5 coverage, carrying the most recent available observation forward. The final main table contains 14 columns covering key information of date identifiers, fishing activity metrics, daily maximum wind speed and gust in both m/s and knots, daily maximum significant wave height, and annual population.</p>
</section>
<section id="sec-weekday" class="level4" data-number="2.3.1.2">
<h4 data-number="2.3.1.2" class="anchored" data-anchor-id="sec-weekday"><span class="header-section-number">2.3.1.2</span> Weekday Behavioral Bias</h4>
<p>Prior to threshold calibration, a weekday bias analysis was conducted to determine whether fishing activity exhibited systematic day-of-week patterns unrelated to climate conditions. Mean population-adjusted lobster trip rates and the proportion of days with any reported lobster activity were computed for each day of the week across the full 40-year study period.</p>
<p>The analysis revealed a pronounced decline in fishing activity on Sunday relative to all other days of the week. The mean CSL trip rate for just Sundays had a value of 0.016 trips per 1,000 people compared to a range of 0.034 to 0.046 on all other weekdays, and a day-active rate of 32.1% compared to 54.4% to 62.8% on other days. This pattern is consistent with traditions of the United States Virgin Islands, where a decrease in labor on Sunday is culturally normative and not a response to environmental conditions. Sunday observations were therefore excluded from the climate threshold validation analysis to prevent behavioral suppression from contaminating the climate signal. Sunday observations were retained within the Fishable Days Index construction itself, as the index measures climate-based fishability rather than observed fishing behavior.</p>
</section>
<section id="fdi-definition-and-threshold-selection" class="level4" data-number="2.3.1.3">
<h4 data-number="2.3.1.3" class="anchored" data-anchor-id="fdi-definition-and-threshold-selection"><span class="header-section-number">2.3.1.3</span> FDI Definition and Threshold Selection</h4>
<p>The Fishable Days Index (<em>FDI</em>) is defined as a binary daily indicator equal to one (<em>FDI = 1</em> on safe days) on days when environmental conditions are consistent with safe small-vessel lobster fishing operations, otherwise FDI is equal to zero (<em>FDI = 0</em> on unsafe days). For the St.&nbsp;Croix CSL fishery, the index is determined by two simultaneous climate conditions: daily maximum wind speed must not exceed a specified limit, and daily maximum significant wave height must not exceed a separate specified limit. Since lobster fishing in St.&nbsp;Croix is open year-round with no regulatory seasonal closure, the FDI contains no regulatory component and is determined entirely by the environmental conditions. Therefore, the annual FDI for any given season is the sum of daily FDI values over a 365-day calendar year.</p>
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Heatmap of threshold sensitivity analysis for varying fishable day weather conditions
</figcaption>
</figure>
</div>
<p>Initial threshold values were drawn from the small vessel operability literature. Wind speeds at or above 20 knots (approximately 10.3 m/s) are widely cited as the threshold above which small craft advisories apply in United States coastal waters, and significant wave heights above 2.0 to 2.5 meters are considered the upper operational limit for vessels typically used in St.&nbsp;Croix lobster fisheries. These values were used initially as starting parameters and evaluated against observed fishing activity data.</p>
</section>
<section id="threshold-validation" class="level4" data-number="2.3.1.4">
<h4 data-number="2.3.1.4" class="anchored" data-anchor-id="threshold-validation"><span class="header-section-number">2.3.1.4</span> Threshold Validation</h4>
<p>The selected thresholds were validated by testing whether days classified as fishable demonstrated higher population-adjusted lobster fishing activity than days classified as unfishable and validated with the fishing report data. Sunday observations were excluded from this analysis as described previously in <a href="#sec-weekday" class="quarto-xref"><span>Section 2.3.1.2</span></a>. This validation compared mean CSL trip rates per 1,000 people and the proportion of days with any reported lobster activity between the two FDI categories.</p>
<p>Using the final thresholds (8.5 m/s and 1.75 m), fishable days had an average CSL trip rate of 0.044 trips per 1,000 people compared to 0.039 on unfishable days, and an active-day rate of 62.5% in contrast to 56.8% on unfishable days. This difference is understood to be conservative relative to what the true climate signal likely produces. The privacy-based censoring rule applied to the fishing report data suppresses observations to zero on any day with fewer than three individual fisher reports. This censoring feature disproportionately affects days near the threshold boundary, where marginal fishing conditions may motivate only one or two fishers to go out, which are the most informative observations for threshold calibration. Therefore, the true separation between fishable and unfishable days is likely greater than these validation statistics suggest.</p>
<p>The sensitivity of the validation result to the threshold values was additionally assessed by identifying that wind speed is the binding constraint in the St.&nbsp;Croix context. Inspection of the sensitivity heatmap reveals that varying the wave threshold from 1.5 to 2.5 meters at a fixed wind threshold of 8.5 m/s changes the fishable day rate by only 4.8 percentage points (52.7% to 57.5%), while varying the wind threshold from 7.5 to 13.0 m/s at a fixed wave height of 1.75 meters produces a range from 34.6% to 81.7%.</p>
</section>
</section>
<section id="methodology-for-pricing-the-weather-derivative" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="methodology-for-pricing-the-weather-derivative"><span class="header-section-number">2.3.2</span> Methodology for Pricing the Weather Derivative</h3>
<section id="contract-purpose-and-pricing-logic" class="level4" data-number="2.3.2.1">
<h4 data-number="2.3.2.1" class="anchored" data-anchor-id="contract-purpose-and-pricing-logic"><span class="header-section-number">2.3.2.1</span> Contract purpose and pricing logic</h4>
<p>The agreement shifts the risk of adverse weather conditions from the derivative buyer to the seller. The contract will not track the actual day-to-day business loss. In contrast, it observes a weather-based index. The design is based on the essential structure of weather derivatives and index insurance. Buyer pays a premium upfront <span class="citation" data-cites="alaton2002 cao2004">(<a href="capstone.html#ref-alaton2002" role="doc-biblioref">Alaton, Djehiche, and Stillberger 2002</a>; <a href="capstone.html#ref-cao2004" role="doc-biblioref">Cao and Wei 2004</a>)</span>. If the index exceeds the trigger threshold during the contract period, the seller makes the contract payment. The contract reduces loss-adjustment costs by generating objective settlements from the recorded weather data and a priori estimated losses instead of from audited firm losses <span class="citation" data-cites="bems2021 worldbank2023">(<a href="capstone.html#ref-bems2021" role="doc-biblioref">Bemš and Aydin 2021</a>; <a href="capstone.html#ref-worldbank2023" role="doc-biblioref">World Bank 2023</a>)</span>.</p>
<p>The contract value in this report is based on an actuarial expected payoff. Since the underlying weather variable is not traded in deep or futures markets, the choice of a predetermined payoff fits well with weather derivatives. Earlier research applies identical expected loss analysis reasoning for temperature, rainfall, and agricultural weather-index contracts <span class="citation" data-cites="alaton2002 bems2021 richards2004">(<a href="capstone.html#ref-alaton2002" role="doc-biblioref">Alaton, Djehiche, and Stillberger 2002</a>; <a href="capstone.html#ref-bems2021" role="doc-biblioref">Bemš and Aydin 2021</a>; <a href="capstone.html#ref-richards2004" role="doc-biblioref">Richards, Manfredo, and Sanders 2004</a>)</span>. Some other pricing models can be mentioned as well, e.g.&nbsp;equilibrium, indifference, or copula-based approaches. However, the actuarial approach provides a clear starting point and aligns with available data and the objective of pricing a fishability-based trigger from past weather conditions <span class="citation" data-cites="bressan2021 cao2004 xu2008">(<a href="capstone.html#ref-bressan2021" role="doc-biblioref">Bressan and Romagnoli 2021</a>; <a href="capstone.html#ref-cao2004" role="doc-biblioref">Cao and Wei 2004</a>; <a href="capstone.html#ref-xu2008" role="doc-biblioref">Xu, Odening, and Musshoff 2008</a>)</span>.</p>
</section>
<section id="index-definition-and-contract-trigger" class="level4" data-number="2.3.2.2">
<h4 data-number="2.3.2.2" class="anchored" data-anchor-id="index-definition-and-contract-trigger"><span class="header-section-number">2.3.2.2</span> Index definition and contract trigger</h4>
<p>Let the contract cover <span class="math inline">\(T\)</span> calendar days. For each day <span class="math inline">\(j\)</span>, define an indicator variable <span class="math inline">\(X_j\)</span>. Set <span class="math inline">\(X_j=1\)</span> when observed weather conditions support fishing on day <span class="math inline">\(j\)</span>. Set <span class="math inline">\(X_j=0\)</span> when weather conditions do not support fishing. The total number of fishable days will be counted by the contract over the entire window. Through this index, a noisy weather sequence is reduced to one contract level quantity that is easily priced by the seller and interpretable by the buyer. The cited framework is consonant with standard weather-derivative design, whereby pay-off is based on a transparent index rather than on realized revenue or profit <span class="citation" data-cites="bems2021 jewson2005 worldbank2023">(<a href="capstone.html#ref-bems2021" role="doc-biblioref">Bemš and Aydin 2021</a>; <a href="capstone.html#ref-jewson2005" role="doc-biblioref">Jewson, Brix, and Ziehmann 2005</a>; <a href="capstone.html#ref-worldbank2023" role="doc-biblioref">World Bank 2023</a>)</span>.</p>
<p>The seasonal fishable-day index is <span class="math inline">\(N=\sum\limits_{j=1}^{n}X_i\)</span>. Here, <span class="math inline">\(N\)</span> counts the number of fishable days in the contract period. Let <span class="math inline">\(K\)</span> denote the strike on fishable days. The contract triggers when fishable days fall below the strike. In mathematical form, the trigger event equals <span class="math inline">\(N&lt;K\)</span>. That event defines the “limiting” or threshold-crossing event for the contract. A higher strike makes the trigger easier to hit. A lower strike makes the trigger harder to hit <span class="citation" data-cites="worldbank2023">(<a href="capstone.html#ref-worldbank2023" role="doc-biblioref">World Bank 2023</a>)</span>.</p>
</section>
<section id="historical-estimation-of-daily-fishability-probabilities" class="level4" data-number="2.3.2.3">
<h4 data-number="2.3.2.3" class="anchored" data-anchor-id="historical-estimation-of-daily-fishability-probabilities"><span class="header-section-number">2.3.2.3</span> Historical estimation of daily fishability probabilities</h4>
<p>For every contract day, we estimate the fishable-day probability. Let <span class="math inline">\(p_j\)</span> represent the probability that day <span class="math inline">\(j\)</span> is fishable. The <span class="math inline">\(p_j\)</span> estimates take place after the index classifies each historical day as either fishable or non-fishable. In effect, we compute one empirical probability for every calendar day in the contract window, pooling the same month-day across historical years. That measure saves seasonality. In addition, it gives January and September distinct probabilities. This step is important because weather derivatives usually require careful treatment of seasonality and calendar structure prior to pricing <span class="citation" data-cites="alaton2002 jewson2005">(<a href="capstone.html#ref-alaton2002" role="doc-biblioref">Alaton, Djehiche, and Stillberger 2002</a>; <a href="capstone.html#ref-jewson2005" role="doc-biblioref">Jewson, Brix, and Ziehmann 2005</a>)</span>.</p>
<p>Instead of imposing a single probability common to every day, we allow every day to have its own estimated probability <span class="math inline">\(p_j\)</span>. This flexibility inspires the Poisson-binomial model. All daily probabilities would have to be matched by the ordinary binomial model. The Poisson-binomial model can handle independent daily Bernoulli trials with unequal success probabilities, which fits a seasonal weather calendar much better <span class="citation" data-cites="biscarri2018 chen1997 hong2013">(<a href="capstone.html#ref-biscarri2018" role="doc-biblioref">Biscarri, Zhao, and Brunner 2018</a>; <a href="capstone.html#ref-chen1997" role="doc-biblioref">Chen and Liu 1997</a>; <a href="capstone.html#ref-hong2013" role="doc-biblioref">Hong 2013</a>)</span>.</p>
</section>
</section>
<section id="poisson-binomial-model" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="poisson-binomial-model"><span class="header-section-number">2.3.3</span> Poisson-Binomial Model</h3>
<section id="why-this-model-fits-the-problem" class="level4" data-number="2.3.3.1">
<h4 data-number="2.3.3.1" class="anchored" data-anchor-id="why-this-model-fits-the-problem"><span class="header-section-number">2.3.3.1</span> Why this model fits the problem</h4>
<p>The Poisson-binomial distribution signifies the total of independent Bernoulli variables that need not share the same success probability. It harmonizes with the contractual weather-based index in a natural fashion as there are predefined conditions that define total fishable days. Every day has its own historical fishability probability <span class="math inline">\(p_j\)</span>. After considering the daily indicators, the model considered daily probabilities as independent and treats them as Bernoulli variables (Fishable or Non-fishable). The seasonal count <span class="math inline">\(N\)</span> was made to follow a Poisson-binomial distribution. Research in statistics on this distribution has established the theory, computation and use of a distribution with a trial probability that varies <span class="citation" data-cites="chen1997 hong2013">(<a href="capstone.html#ref-chen1997" role="doc-biblioref">Chen and Liu 1997</a>; <a href="capstone.html#ref-hong2013" role="doc-biblioref">Hong 2013</a>)</span>. Formally, <span class="math inline">\(X_j\sim\text{Bernoulli}(p_j), \quad j=1,2,\dots, T\)</span> and assume independence across days, <span class="math inline">\(N=\sum\limits_{j=1}^{T} X_j \sim \text{Poisson-Binomial}(p_1,  p_2, \dots, p_T)\)</span>. The expected number of fishable days follows, <span class="math inline">\(E[N]=\sum\limits_{j=1}^{T}p_j\)</span>. The variance follows, <span class="math inline">\(Var(N)=\sum\limits_{j=1}^T(1-p_j)\)</span>.These moments summarize the center and spread of the seasonal fishable-day distribution under the independence assumption.</p>
</section>
<section id="probability-of-mass-function" class="level4" data-number="2.3.3.2">
<h4 data-number="2.3.3.2" class="anchored" data-anchor-id="probability-of-mass-function"><span class="header-section-number">2.3.3.2</span> Probability of mass function</h4>
<p>The exact probability that the season ends with exactly 𝑛 fishable days equals <span class="math display">\[P(N=n)=\sum\limits_{A\epsilon F_n} \prod\limits_{j\epsilon Ap_j}(1-p_j), \quad n=1,2,\dots, T\]</span></p>
<p>Where <span class="math inline">\(F_n\)</span> denotes the collection of all subsets of <span class="math inline">\(\{1, \dots, T\}\)</span> that contain exactly <span class="math inline">\(n\)</span> elements. This equation sums up the probability of every possible path that produces exactly <span class="math inline">\(n\)</span> fishable days. The equation gives the full probability mass function of the contract index. It also provides the foundation for trigger probability and price calculations <span class="citation" data-cites="chen1997 fernandez2010 hong2013">(<a href="capstone.html#ref-chen1997" role="doc-biblioref">Chen and Liu 1997</a>; <a href="capstone.html#ref-fernandez2010" role="doc-biblioref">Fernandez and Williams 2010</a>; <a href="capstone.html#ref-hong2013" role="doc-biblioref">Hong 2013</a>)</span>.</p>
<p>This report does not enumerate all subsets directly because that route grows expensive when <span class="math inline">\(T\)</span> becomes large. Instead, the code uses recursive convolution, which updates the distribution one day at a time. Let <span class="math inline">\(f_m(n)\)</span> denote the probability of obtaining <span class="math inline">\(n\)</span> fishable days after the first <span class="math inline">\(m\)</span> contract days. Start with <span class="math inline">\(f_0(0)=1, f_0(n) = 0, \text{ for } n&gt;0\)</span>.</p>
<p>Then update with <span class="math inline">\(f_m(n)=(1-p_m)f_{m-1}(n) + p_mf_{m-1}(n-1), \text{ for } m=1,2,\dots, T\)</span> for all valid <span class="math inline">\(n\)</span>. After the last update, <span class="math inline">\(f_T(n)=P(N=n)\)</span>. Statistical studies show that recursive and Fourier-based methods provide exact or highly efficient ways to compute the Poisson-binomial distribution in applied work <span class="citation" data-cites="biscarri2018 chen1997 fernandez2010 hong2013">(<a href="capstone.html#ref-biscarri2018" role="doc-biblioref">Biscarri, Zhao, and Brunner 2018</a>; <a href="capstone.html#ref-chen1997" role="doc-biblioref">Chen and Liu 1997</a>; <a href="capstone.html#ref-fernandez2010" role="doc-biblioref">Fernandez and Williams 2010</a>; <a href="capstone.html#ref-hong2013" role="doc-biblioref">Hong 2013</a>)</span>.</p>
</section>
</section>
<section id="limiting-probability-equation" class="level3" data-number="2.3.4">
<h3 data-number="2.3.4" class="anchored" data-anchor-id="limiting-probability-equation"><span class="header-section-number">2.3.4</span> Limiting Probability Equation</h3>
<section id="trigger-probability-under-the-strike-limit" class="level4" data-number="2.3.4.1">
<h4 data-number="2.3.4.1" class="anchored" data-anchor-id="trigger-probability-under-the-strike-limit"><span class="header-section-number">2.3.4.1</span> Trigger probability under the strike limit</h4>
<p>The key risk quantity in this contract comes from the probability that fishable days will fall below the strike. That probability drives the contract price directly since the payoff uses a fixed indemnity. Let <span class="math inline">\(\Psi(K)\)</span> denote the limiting probability of the contract trigger.</p>
<p>Then <span class="math inline">\(\Psi(K)=P(N&lt;K)=\sum\limits_{n=0}^{K-1}P(N=n)\)</span>. This equation gives the cumulative lower-tail probability of the Poisson-binomial distribution up to one day below the number of days associated with the strike percentage times the mean fishable days. It answers the central pricing question: how often would the season fail to reach the minimum acceptable number of fishable days? <span class="citation" data-cites="biscarri2018 fernandez2010">Hong (<a href="capstone.html#ref-hong2013" role="doc-biblioref">2013</a>)</span>. If the strike comes from a percentage of expected fishable days, the model can define <span class="math inline">\(K_s=round(s\mu), \mu=E[N]=\sum\limits_{j=1}^Tp_j\)</span></p>
<p>where the value of strike percentage is explored from 0.80 to 0.99 The strike percentage makes the conversion into an integer number of fishable days. The model then calculates <span class="math inline">\(\Psi(K)\)</span> for each level of strike. This threshold design is consistent with common weather index practice where the contract maps an index threshold into a trigger probability and then to an expected payout.</p>
</section>
<section id="payoff-design" class="level4" data-number="2.3.4.2">
<h4 data-number="2.3.4.2" class="anchored" data-anchor-id="payoff-design"><span class="header-section-number">2.3.4.2</span> Payoff Design</h4>
</section>
<section id="general-payoff-function" class="level4" data-number="2.3.4.3">
<h4 data-number="2.3.4.3" class="anchored" data-anchor-id="general-payoff-function"><span class="header-section-number">2.3.4.3</span> General payoff function</h4>
<p>A weather derivative price starts with the payoff function. Let <span class="math inline">\(G(N)\)</span> denote the contract payoff at expiration as a function of the seasonal fishable-day count <span class="math inline">\(N\)</span>. The most general actuarial pricing equation then discounts the expected payoff back to the pricing date: <span class="math display">\[V_0=e^{-r\tau}E[G(N)]=e^{-r\tau}\sum\limits_{n=0}^TG(n)P(N=n)\]</span></p>
<p>Where <span class="math inline">\(r\)</span> denotes the continuously compounded risk-free rate and <span class="math inline">\(\tau\)</span> denotes the contract length in years. This expected-payoff structure sits at the center of actuarial and burn-analysis pricing for weather-index products <span class="citation" data-cites="alaton2002 jewson2005 taib2012 worldbank2023">(<a href="capstone.html#ref-alaton2002" role="doc-biblioref">Alaton, Djehiche, and Stillberger 2002</a>; <a href="capstone.html#ref-jewson2005" role="doc-biblioref">Jewson, Brix, and Ziehmann 2005</a>; <a href="capstone.html#ref-taib2012" role="doc-biblioref">Taib and Benth 2012</a>; <a href="capstone.html#ref-worldbank2023" role="doc-biblioref">World Bank 2023</a>)</span>.</p>
</section>
<section id="fixed-payout-contract-used-in-the-code" class="level4" data-number="2.3.4.4">
<h4 data-number="2.3.4.4" class="anchored" data-anchor-id="fixed-payout-contract-used-in-the-code"><span class="header-section-number">2.3.4.4</span> Fixed-payout contract used in the code</h4>
<p>We use a predetermined and fixed payout. The payout would be issued if the total number of days in the contract period falls below the strike. Let <span class="math inline">\(L\)</span> denote that payout. Then the payoff function equals <span class="math inline">\(G(N)=L1(N&lt;K)\)</span> where <span class="math inline">\(1(N&lt;K)\)</span> equals 1 when the trigger hits, and 0 otherwise.</p>
<p>Under this design, the weather derivative price simplifies to <span class="math inline">\(V_0=e^{-r\tau}LP(N&lt;K)=e^{-r\tau}L\Psi K\)</span>. This form makes the pricing logic very clear. The discount factor handles time value. The limiting probability handles event likelihood. The payout level handles contract severity. Multiply the three terms, and the model returns the fair actuarial price <span class="citation" data-cites="jewson2005 taib2012 worldbank2023">(<a href="capstone.html#ref-jewson2005" role="doc-biblioref">Jewson, Brix, and Ziehmann 2005</a>; <a href="capstone.html#ref-taib2012" role="doc-biblioref">Taib and Benth 2012</a>; <a href="capstone.html#ref-worldbank2023" role="doc-biblioref">World Bank 2023</a>)</span>.</p>
<p>In implementation, the code sets the fixed payout from the shortfall between the expected fishable-day count and the strike, multiplied by average profit per day as <span class="math inline">\(L=(\mu-K)\pi^-, \text{ for }K\le\mu\)</span>. Where <span class="math inline">\(\pi^-\)</span> denotes average profit per fishable day. If the analyst wants a payout rate <span class="math inline">\(\alpha\)</span>, then the formula becomes <span class="math inline">\(L=\alpha(\mu-K)\pi^-\)</span>. This rule creates a simple and transparent contract. It does not reward larger realized shortfalls once the trigger fires. It only pays one fixed amount per strike. That feature keeps pricing simple, but it also sacrifices some loss sensitivity <span class="citation" data-cites="kath2018 worldbank2011 worldbank2023">(<a href="capstone.html#ref-kath2018" role="doc-biblioref">Kath et al. 2018</a>; <a href="capstone.html#ref-worldbank2011" role="doc-biblioref">World Bank 2011</a>, <a href="capstone.html#ref-worldbank2023" role="doc-biblioref">2023</a>)</span>.</p>
</section>
<section id="step-by-step-pricing-procedure" class="level4" data-number="2.3.4.5">
<h4 data-number="2.3.4.5" class="anchored" data-anchor-id="step-by-step-pricing-procedure"><span class="header-section-number">2.3.4.5</span> Step-by-Step Pricing Procedure</h4>
</section>
<section id="build-the-daily-index" class="level4" data-number="2.3.4.6">
<h4 data-number="2.3.4.6" class="anchored" data-anchor-id="build-the-daily-index"><span class="header-section-number">2.3.4.6</span> Build the daily index</h4>
<p>The meteorological department begins recording daily weather observations. The analyst selects weather thresholds that define what is deemed a fishable day. The wind speed and wave height provide thresholds for our study. Our code assigns each historical day to a fishable or non-fishable label. This step generates the binary series necessary for Bernoulli modeling. The weather-derivative practice usually begins at this stage of index construction, since the derivative settles on the index, not the raw weather variables <span class="citation" data-cites="bems2021 jewson2005 worldbank2023">(<a href="capstone.html#ref-bems2021" role="doc-biblioref">Bemš and Aydin 2021</a>; <a href="capstone.html#ref-jewson2005" role="doc-biblioref">Jewson, Brix, and Ziehmann 2005</a>; <a href="capstone.html#ref-worldbank2023" role="doc-biblioref">World Bank 2023</a>)</span>.</p>
</section>
<section id="estimate-day-specific-probabilities" class="level4" data-number="2.3.4.7">
<h4 data-number="2.3.4.7" class="anchored" data-anchor-id="estimate-day-specific-probabilities"><span class="header-section-number">2.3.4.7</span> Estimate Day-specific probabilities</h4>
<p>Next, the analyst estimates <span class="math inline">\(p_j\)</span> for each calendar day in the contract. The code eliminates February 29 so that the calendar will have 365 days only. This then pools the month-day across all years and calculates that date’s historical fishable frequency. After this step there will be one probability for each contract day. The method allows different seasons to take values independently without forcing all days to value from the same distribution. The Poisson-binomial choice is justified by that feature <span class="citation" data-cites="chen1997 hong2013 jewson2005">(<a href="capstone.html#ref-chen1997" role="doc-biblioref">Chen and Liu 1997</a>; <a href="capstone.html#ref-hong2013" role="doc-biblioref">Hong 2013</a>; <a href="capstone.html#ref-jewson2005" role="doc-biblioref">Jewson, Brix, and Ziehmann 2005</a>)</span>.</p>
</section>
<section id="compute-the-seasonal-distribution" class="level4" data-number="2.3.4.8">
<h4 data-number="2.3.4.8" class="anchored" data-anchor-id="compute-the-seasonal-distribution"><span class="header-section-number">2.3.4.8</span> Compute the seasonal distribution</h4>
<p>Once <span class="math inline">\(p_j\)</span> values have been estimated for the model, the full Poisson-binomial probability mass function for <span class="math inline">\(N\)</span> is computed. Each recursive update starts on day 1 and folds one day into the distribution repeatedly. The model has a probability for each possible total fishable-day count from 0 to <span class="math inline">\(T\)</span>. A full distribution conveys more information than just the means. It enables the analyst to calculate trigger probabilities in the lower tail, expected payoffs, and premium sensitivity across various strike levels <span class="citation" data-cites="biscarri2018 fernandez2010 hong2013">(<a href="capstone.html#ref-biscarri2018" role="doc-biblioref">Biscarri, Zhao, and Brunner 2018</a>; <a href="capstone.html#ref-fernandez2010" role="doc-biblioref">Fernandez and Williams 2010</a>; <a href="capstone.html#ref-hong2013" role="doc-biblioref">Hong 2013</a>)</span>.</p>
</section>
<section id="interpretation-of-the-price" class="level4" data-number="2.3.4.9">
<h4 data-number="2.3.4.9" class="anchored" data-anchor-id="interpretation-of-the-price"><span class="header-section-number">2.3.4.9</span> Interpretation of the Price</h4>
<p>This price represents the current worth of the expected contract payoff calculated using the historical probability model. The price omits transaction costs, profit loading, administrative charges, or a market price of weather risk. Research on weather derivatives indicates that incomplete-market settings can justify alternative pricing rules, including the use of equilibrium or indifference methods when traders demand compensation for non-hedgeable weather risk. However, our Poisson-binomial price based on actuarial technique is suitably transparent and represents a fair-value benchmark <span class="citation" data-cites="alaton2002 cao2004 richards2004 xu2008">(<a href="capstone.html#ref-alaton2002" role="doc-biblioref">Alaton, Djehiche, and Stillberger 2002</a>; <a href="capstone.html#ref-cao2004" role="doc-biblioref">Cao and Wei 2004</a>; <a href="capstone.html#ref-richards2004" role="doc-biblioref">Richards, Manfredo, and Sanders 2004</a>; <a href="capstone.html#ref-xu2008" role="doc-biblioref">Xu, Odening, and Musshoff 2008</a>)</span>.</p>
<p>As the strike percentage increases, the contract is triggered more easily because the season must meet a higher target for fishable days. Hence, the lower tail cumulative probability increases. Beneath a fixed payout design, the premium increases since the contract pays the same amount more often. With a shortfall design, the premium usually rises even faster as the contract pays out more often and can pay larger amounts. The upward pattern is what standard derivative and insurance intuition suggests: more coverage costs more <span class="citation" data-cites="kath2018 worldbank2023">(<a href="capstone.html#ref-kath2018" role="doc-biblioref">Kath et al. 2018</a>; <a href="capstone.html#ref-worldbank2023" role="doc-biblioref">World Bank 2023</a>)</span>.</p>
</section>
<section id="results-and-findings" class="level4" data-number="2.3.4.10">
<h4 data-number="2.3.4.10" class="anchored" data-anchor-id="results-and-findings"><span class="header-section-number">2.3.4.10</span> Results and Findings</h4>
</section>
<section id="threshold-sensitivity-and-final-index-choice" class="level4" data-number="2.3.4.11">
<h4 data-number="2.3.4.11" class="anchored" data-anchor-id="threshold-sensitivity-and-final-index-choice"><span class="header-section-number">2.3.4.11</span> Threshold sensitivity and final index choice</h4>
<p>The threshold sensitivity analysis demonstrates (Table 1) that the fishable-day index is quite responsive to the chosen wind and wave cutoffs. Reduced thresholds yield a significantly more limiting index, where most days are classified as non-fishable. A higher threshold was identified as more permissive (classifying most and almost all days as fishable). That methodology section states that the daily fishability indicator is determined by whether both the wind speed and the wave height do not exceed the cutoffs chosen. The sensitivity table indicates that for the strictest threshold pair, the percent of fishable days is around 33.35% (7.5 <span class="math inline">\(m/s\)</span>, 1.5 <span class="math inline">\(m\)</span>). However, for the loosest threshold pair, the percent of fishable days is around 98.47% (13.0 <span class="math inline">\(m/s\)</span>, 2.5 <span class="math inline">\(m\)</span>). The average yearly fishable day index moves in the same manner. It increases from roughly 121.80 days to 359.60 days. The yearly deviation does not monotonically shift throughout all threshold pairs, but it does drop when the threshold becomes very loose and ends up with the index approaching the ceiling of the annual calendar, leaving less room for interannual fluctuation.</p>
<div style="page-break-after: always;"></div>
<div class="cell">
<div id="tbl-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Threshold sensitivity analysis for fishable-day index construction
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-abc5929a{}.cl-abbc0162{font-family:'DejaVu Sans';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-abbc0176{font-family:'DejaVu Sans';font-size:9pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-abbf96c4{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-abbfccc0{width:1.12in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccd4{width:1.068in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccd5{width:1.031in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccde{width:1.232in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccdf{width:1.001in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcce0{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcce8{width:1.12in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcce9{width:1.068in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccf2{width:1.031in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccf3{width:1.232in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccf4{width:1.001in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccf5{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccfc{width:1.12in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccfd{width:1.068in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfccfe{width:1.031in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd06{width:1.232in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd07{width:1.001in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd10{width:0.799in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd11{width:1.12in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd1a{width:1.068in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd1b{width:1.031in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd24{width:1.232in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd25{width:1.001in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abbfcd2e{width:0.799in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-abc5929a"><thead><tr style="overflow-wrap:break-word;"><th class="cl-abbfccc0"><p class="cl-abbf96c4"><span class="cl-abbc0162">Wind (m/s)</span></p></th><th class="cl-abbfccd4"><p class="cl-abbf96c4"><span class="cl-abbc0162">Wind (kts)</span></p></th><th class="cl-abbfccd5"><p class="cl-abbf96c4"><span class="cl-abbc0162">Wave (m)</span></p></th><th class="cl-abbfccde"><p class="cl-abbf96c4"><span class="cl-abbc0162">Fishable (%)</span></p></th><th class="cl-abbfccdf"><p class="cl-abbf96c4"><span class="cl-abbc0162">Mean FDI</span></p></th><th class="cl-abbfcce0"><p class="cl-abbf96c4"><span class="cl-abbc0162">SD FDI</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-abbfcce8"><p class="cl-abbf96c4"><span class="cl-abbc0162">7.50</span></p></td><td class="cl-abbfcce9"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.58</span></p></td><td class="cl-abbfccf2"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.50</span></p></td><td class="cl-abbfccf3"><p class="cl-abbf96c4"><span class="cl-abbc0162">33.35</span></p></td><td class="cl-abbfccf4"><p class="cl-abbf96c4"><span class="cl-abbc0162">121.80</span></p></td><td class="cl-abbfccf5"><p class="cl-abbf96c4"><span class="cl-abbc0162">21.29</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">7.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.58</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.75</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">34.56</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">126.20</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.23</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">7.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.58</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.00</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">34.83</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">127.18</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.17</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">7.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.58</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.25</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">34.87</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">127.35</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.18</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">7.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.58</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">34.91</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">127.48</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.23</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">8.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">16.52</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">52.69</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">192.42</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">21.70</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfcd11"><p class="cl-abbf96c4"><span class="cl-abbc0176">8.50</span></p></td><td class="cl-abbfcd1a"><p class="cl-abbf96c4"><span class="cl-abbc0176">16.52</span></p></td><td class="cl-abbfcd1b"><p class="cl-abbf96c4"><span class="cl-abbc0176">1.75</span></p></td><td class="cl-abbfcd24"><p class="cl-abbf96c4"><span class="cl-abbc0176">56.67</span></p></td><td class="cl-abbfcd25"><p class="cl-abbf96c4"><span class="cl-abbc0176">206.95</span></p></td><td class="cl-abbfcd2e"><p class="cl-abbf96c4"><span class="cl-abbc0176">23.95</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">8.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">16.52</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.00</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">57.31</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">209.30</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">24.07</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">8.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">16.52</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.25</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">57.43</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">209.72</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">24.04</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">8.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">16.52</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">57.47</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">209.88</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">24.09</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">10.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.44</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">62.59</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">228.58</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.78</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">10.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.44</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.75</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">80.15</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">292.68</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.50</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">10.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.44</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.00</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">85.61</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">312.62</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">12.40</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">10.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.44</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.25</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">86.40</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">315.50</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">11.84</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">10.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.44</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">86.51</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">315.90</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">11.96</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">11.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.35</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">62.65</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">228.78</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.85</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">11.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.35</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.75</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">81.67</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">298.23</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.62</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">11.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.35</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.00</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">91.58</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">334.42</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">8.84</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">11.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.35</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.25</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">96.21</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">351.32</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">5.33</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">11.50</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">22.35</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">97.41</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">355.72</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">4.49</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">13.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">25.27</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">62.65</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">228.78</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">19.85</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">13.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">25.27</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">1.75</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">81.67</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">298.25</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">14.59</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">13.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">25.27</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.00</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">91.67</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">334.75</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">8.73</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">13.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">25.27</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.25</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">96.54</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">352.52</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">5.26</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abbfccfc"><p class="cl-abbf96c4"><span class="cl-abbc0162">13.00</span></p></td><td class="cl-abbfccfd"><p class="cl-abbf96c4"><span class="cl-abbc0162">25.27</span></p></td><td class="cl-abbfccfe"><p class="cl-abbf96c4"><span class="cl-abbc0162">2.50</span></p></td><td class="cl-abbfcd06"><p class="cl-abbf96c4"><span class="cl-abbc0162">98.47</span></p></td><td class="cl-abbfcd07"><p class="cl-abbf96c4"><span class="cl-abbc0162">359.60</span></p></td><td class="cl-abbfcd10"><p class="cl-abbf96c4"><span class="cl-abbc0162">0.00</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>The pair of 8.50 <span class="math inline">\(m/s\)</span> for wind and 1.75 m for wave height selected provides a balanced index (Table 1). This configuration results in 56.67% fishable days, a mean annual fishable day count of 206.95, and an annual standard deviation of 23.95 over the total historical record. This selection bypasses the two weak extremes. If the threshold is very strict, it will classify too many days as non-fishable and compress the commercial meaning of the index. A highly lenient threshold would deem nearly every day suitable for fishing, weakening the derivative trigger itself. The chosen threshold thus conserves enough non-fishable days to generate variation in risk, and nevertheless, incurs plausible operating conditions. The chosen approach has a methodological objective of developing a weather-based index that accounts for actual fishing access rather than merely the meteorological variation directly.</p>
</section>
<section id="contract-window-summary-and-annual-fishable-day-distribution" class="level4" data-number="2.3.4.12">
<h4 data-number="2.3.4.12" class="anchored" data-anchor-id="contract-window-summary-and-annual-fishable-day-distribution"><span class="header-section-number">2.3.4.12</span> Contract window summary and annual fishable-day distribution</h4>
<p>The contract is for the full calendar year, January 1 to December 31. This design gives a 365-day window of exposure that covers the entire seasonal cycle in marine weather. The probability summary reveals that the range over the contract period is likely 206.80 fishable days. According to the annual contract FDI summary (<a href="#tbl-2" class="quarto-xref">Table&nbsp;<span>2.2</span></a>), the mean is 206.78 days with a standard deviation of 23.94 days. The two values are nearly equal. This close agreement suggests that the daily empirical probabilities correspond well to the historical annual counts. Essentially, the methodology’s historical daily-probability construction produces the long-run average fishable day within a year with little error.</p>
<div id="tbl-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Contract design and summary statistics for the annual fishable-day derivative
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Contract start date</td>
<td style="text-align: left;">01-01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Contract end date</td>
<td style="text-align: left;">12-31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Contract length (days)</td>
<td style="text-align: left;">365</td>
</tr>
<tr class="even">
<td style="text-align: left;">Contract length (years)</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expected fishable days during contract</td>
<td style="text-align: left;">206.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean contract FDI (days)</td>
<td style="text-align: left;">206.78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard deviation of contract FDI (days)</td>
<td style="text-align: left;">23.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Average profit per fishable day ($)</td>
<td style="text-align: left;">330.00</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 207 fishable days mean the selected threshold, supports fishing on roughly 57% of the days in a normal year (<a href="#tbl-2" class="quarto-xref">Table&nbsp;<span>2.2</span></a>). An inter-annual variability of around 24 days is suggested by the standard deviation. This amount is relevant for pricing. A derivative contract must ensure sufficient dispersion in the index to create a meaningful lower- tail trigger probability. Here, the yearly difference facilitates the need. Simultaneously, the spread does not appear to be so large as to indicate an unstable index or poorly defined index. Consequently, this measure assesses fishable days and can be used as an underlying contract variable.</p>
</section>
<section id="seasonal-pattern-in-daily-fishability-probability" class="level4" data-number="2.3.4.13">
<h4 data-number="2.3.4.13" class="anchored" data-anchor-id="seasonal-pattern-in-daily-fishability-probability"><span class="header-section-number">2.3.4.13</span> Seasonal pattern in daily fishability probability</h4>
<p>The daily probability plot shows a clear seasonal pattern within the year. It follows from the methodology section that the model estimates probability 𝑃𝑗 separately for each contract day, pooling the same month-day over years. The curve in the plot does not remain flat. It demonstrates a strong seasonal structure instead. In the early season, the probabilities of being able to fish daily are around 0.35 to 0.50. Those probabilities rise during late winter and spring, sharply dip around mid-contract year, and then rise again towards a second high-probability period later in the year (<a href="#fig-2" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>).</p>
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Daily probability of a fishable day during the contract window
</figcaption>
</figure>
</div>
<p>This trend comes with two important repercussions. In the first place, the contract index does not follow a stationary Bernoulli process with a daily constant probability. The Poisson-binomial framework implemented in the methodology is justified by that result which allows unequal probability. Seasonal structure shows that risk is not spread evenly over the year, but has months dedicated to risk. A concentrated risk window with additional non-fishable days is marked by a mid-year dip. This period at the end of the year is under a high probability window. The seasonal variation influences the annual fishable days distribution of annual fishable days and the lower-tail trigger probability. The findings thus confirm that we were right to not homogenize all days into one average probability and preserve calendar-day heterogeneity.</p>
<p>According to the plot, it is observed that during the least favorable periods, many daily probabilities are well below 0.5, while during the most favorable periods, probabilities rise above 0.8. This range shows a strong seasonal contrast. The contrasting elements enhance the substance of the index. Furthermore, it upholds the pricing logic as seasonal structure contracts can capture real operational exposure better than those based on constant average hazard contracts.</p>
</section>
<section id="strike-design-and-trigger-behavior" class="level4" data-number="2.3.4.14">
<h4 data-number="2.3.4.14" class="anchored" data-anchor-id="strike-design-and-trigger-behavior"><span class="header-section-number">2.3.4.14</span> Strike design and trigger behavior</h4>
<p>The pricing analysis assesses strike levels between 80% and 95% of the expected average number of fishable days calculated over a one-year contract period. This design directly ties the available data to user-specified percentage of expected contract fishable days. The subsequent periods between strikes vary from 165 to 196 days (<a href="#tbl-3" class="quarto-xref">Table&nbsp;<span>2.3</span></a>). With increasing strike percentage, the trigger threshold moves towards 207 days, which is the expected annual fishing days. This change raises the chances of payout due to increased low-event odds, but results in a lower payout since fewer days are factored into the losses.</p>
<div class="cell">
<div id="tbl-3" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.3: Weather derivative pricing results across strike levels
</figcaption>
<div aria-describedby="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-abf29dc6{table-layout:auto;width:100%;}.cl-abea89f6{font-family:'DejaVu Sans';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-abee38da{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-abee5e78{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e79{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e82{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e83{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e8c{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e8d{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e8e{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e96{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e97{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5e98{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5ea0{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5ea1{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5ea2{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5eaa{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5eab{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5eb4{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5eb5{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5eb6{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5ebe{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-abee5ebf{background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(0, 0, 0, 1.00);border-top: 0.75pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-abf29dc6"><thead><tr style="overflow-wrap:break-word;"><th class="cl-abee5e78"><p class="cl-abee38da"><span class="cl-abea89f6">Strike (%)</span></p></th><th class="cl-abee5e79"><p class="cl-abee38da"><span class="cl-abea89f6">Strike (days)</span></p></th><th class="cl-abee5e82"><p class="cl-abee38da"><span class="cl-abea89f6">Fixed Payout ($)</span></p></th><th class="cl-abee5e83"><p class="cl-abee38da"><span class="cl-abea89f6">Trigger Prob.</span></p></th><th class="cl-abee5e8c"><p class="cl-abee38da"><span class="cl-abea89f6">Derivative Price ($)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-abee5e8d"><p class="cl-abee38da"><span class="cl-abea89f6">80</span></p></td><td class="cl-abee5e8e"><p class="cl-abee38da"><span class="cl-abea89f6">165</span></p></td><td class="cl-abee5e96"><p class="cl-abee38da"><span class="cl-abea89f6">13,785.75</span></p></td><td class="cl-abee5e97"><p class="cl-abee38da"><span class="cl-abea89f6">0.000002</span></p></td><td class="cl-abee5e98"><p class="cl-abee38da"><span class="cl-abea89f6">0.02</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">81</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">167</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">13,125.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.000004</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">0.06</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">82</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">170</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">12,135.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.000019</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">0.23</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5eb4"><p class="cl-abee38da"><span class="cl-abea89f6">83</span></p></td><td class="cl-abee5eb5"><p class="cl-abee38da"><span class="cl-abea89f6">172</span></p></td><td class="cl-abee5eb6"><p class="cl-abee38da"><span class="cl-abea89f6">11,475.75</span></p></td><td class="cl-abee5ebe"><p class="cl-abee38da"><span class="cl-abea89f6">0.000049</span></p></td><td class="cl-abee5ebf"><p class="cl-abee38da"><span class="cl-abea89f6">0.54</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">84</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">174</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">10,815.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.000119</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">1.24</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">85</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">176</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">10,155.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.000276</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">2.70</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">86</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">178</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">9,495.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.000610</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">5.58</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">87</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">180</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">8,835.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.001289</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">10.98</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">88</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">182</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">8,175.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.002605</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">20.52</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5eb4"><p class="cl-abee38da"><span class="cl-abea89f6">89</span></p></td><td class="cl-abee5eb5"><p class="cl-abee38da"><span class="cl-abea89f6">184</span></p></td><td class="cl-abee5eb6"><p class="cl-abee38da"><span class="cl-abea89f6">7,515.75</span></p></td><td class="cl-abee5ebe"><p class="cl-abee38da"><span class="cl-abea89f6">0.005032</span></p></td><td class="cl-abee5ebf"><p class="cl-abee38da"><span class="cl-abea89f6">36.45</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">90</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">186</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">6,855.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.009303</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">61.46</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">91</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">188</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">6,195.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.016460</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">98.28</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">92</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">190</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">5,535.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.027895</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">148.81</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">93</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">192</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">4,875.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.045302</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">212.86</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">94</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">194</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">4,215.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.070555</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">286.64</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-abee5ea0"><p class="cl-abee38da"><span class="cl-abea89f6">95</span></p></td><td class="cl-abee5ea1"><p class="cl-abee38da"><span class="cl-abea89f6">196</span></p></td><td class="cl-abee5ea2"><p class="cl-abee38da"><span class="cl-abea89f6">3,555.75</span></p></td><td class="cl-abee5eaa"><p class="cl-abee38da"><span class="cl-abea89f6">0.105465</span></p></td><td class="cl-abee5eab"><p class="cl-abee38da"><span class="cl-abea89f6">361.38</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>The probabilities of triggers indicate a strong non-linearity response. The contract gets triggered rarely at lower levels. The prospect of a trigger only has a probability of 0.000002 at 80% strike. Further, it is 0.000004 at 81% and 0.000019 at 82%. These values suggest a nearly dormant contract. Even a very adverse weather year would have to fall well below the long-run mean before the payout condition trigger. As a result, the contract guarantees minimal practical protection in this strike range.</p>
<p>Once the strike crosses above the upper-80% level, the sensitivity of the trigger probability begins to move. It goes up to 0.001289 at 87%, 0.002605 at 88%, and 0.005032 at 89% (<a href="#tbl-3" class="quarto-xref">Table&nbsp;<span>2.3</span></a>). The likelihood then quickly rises in the region of 90% to 95%. At 90%, it reaches 0.009303; at 91%, 0.016460; at 92%, 0.027895; at 93% it reaches 0.045302; at 94%, 0.070555; finally, at 95%, it reaches 0.105465. This pattern is non linear. The upper strike range penetrates further into the core of the annual fishable-day distribution. A slight adjustment in the strike rate, thus, has a larger impact on trigger frequency.</p>
<p>It holds practical significance. A designer who accepts strikes under 88% would probably be selling a product that has no economic relevance as the trigger probably never fires. An option that settles at the money or strikes near 93% to 95% will create a much more active hedging tool. Even at that range, an event-based contract would remain in place, no annual transfer. Consequently, the findings suggest that the upper strike range is the most defensible area for meaningful hedging.</p>
</section>
<section id="derivative-price-profile-across-strike-levels" class="level4" data-number="2.3.4.15">
<h4 data-number="2.3.4.15" class="anchored" data-anchor-id="derivative-price-profile-across-strike-levels"><span class="header-section-number">2.3.4.15</span> Derivative price profile across strike levels</h4>
<p>The continuously rising weather derivative price with respect to strike percentage faces a steep change with respect to strike. The fixed-payout pricing formula, 𝑉0=𝑒−𝑟𝑡𝐿Ψ(𝐾), directly leads to this pattern. As the strike rises, the gap between the expected fishable days and the strike narrows, causing the fixed payout to decline in the current implementation. However, the payout falls faster than the trigger probability rises. This probability effect dominates the price function.</p>
<p>The price is practically nonexistent for low strikes. At 80% the amount is $0.02, at 81% the amount is $0.06, at 82% it is $0.23 and at 83% it is $0.54 (<a href="#tbl-3" class="quarto-xref">Table&nbsp;<span>2.3</span></a>). Even at 86%, it costs under $5.58. The values indicate that lower strike regions generate a very low expected protection value. The contract rarely activates to warrant a significant premium, according to the experts.</p>
<p>The price then increases quickly once the strike enters the low-90% range (<a href="#fig-3" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>). It climbs to $20.52 at 88%, $36.45 at 89%, $61.46 at 90%, $98.28 at 91%, $148.81 at 92%, $212.86 at 93%, $286.64 at 94%, $361.38 at 95%. As a result, the price curve is convex. The derivative becomes markedly more costly as the strike nears the expected annual total fishable days.</p>
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig3.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Trigger probability across strike percentages
</figcaption>
</figure>
</div>
<p>This shape is economically viable. A higher strike position triggers nearer to the midpoint of the annual fishable-day distribution. While the fixed payout amount falls, the payout frequency increases with that move. It can be observed from the results that the rise in trigger probability surpasses the decrease in a benefit size (<a href="#fig-3" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>). That collaboration leads to a sudden rise in the premium curve. As per the model, it is not the fixed payout size but rather triggers probability that drives price over the tested range.</p>
</section>
<section id="joint-interpretation-of-trigger-probability-and-premium" class="level4" data-number="2.3.4.16">
<h4 data-number="2.3.4.16" class="anchored" data-anchor-id="joint-interpretation-of-trigger-probability-and-premium"><span class="header-section-number">2.3.4.16</span> Joint interpretation of trigger probability and premium</h4>
<p>The trigger probability curve and the premium curve both show positive exponential patterns but with different rates. The difference is due to the pricing formula. The premiums reflect the low tail probability and the fixed payout level. In the design under test, the payout decreases as the strike percentage increases. However, the effect of lower tail probability has a stronger influence. The interaction generates a curve for the price per number of fishable days that initially rises smoothly and then increases at a faster rate (<a href="#fig-3" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>; <a href="#fig-4" class="quarto-xref">Figure&nbsp;<span>2.4</span></a>).</p>
<div id="fig-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig4.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Weather derivative Price across strike percentages
</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="discussion" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="discussion"><span class="header-section-number">2.4</span> Discussion</h2>
<p>This project did not explicitly consider related logistics and financial overheads of pricing a weather-based derivative to cover non-fishable days. Here, we discuss some of the logistics the proposed rainy day fisher fund would need to further consider including reinsurance, markups, and pooling risk. To offer the parametric weather-based insurance, the insurer would need to have sufficient funds and ensure that payouts would be rapid upon reaching strike conditions. Unless a fishing community were to develop a reciprocal insurance exchange, through a self-insurance pool with sufficient funds to cover potential payouts, the cost of issuing any parametric insurance policy would also need to include operating expenses and reinsurance. Since this analysis consisted only of a single industry located in a small geographic area, the proposed program could benefit from developing similar frameworks across a wider geographical region or including other types of industries to diversify risk. Such diversification would reduce the expenses of external reinsurance.</p>
<p>The process of pricing a parametric insurance policy serves as a simplified case study and exploration of the fundamental dynamics of pricing parametric insurance. First, we focused on developing a fishable day index as an objective metric evaluated from specific timeseries of meteorological data. Then we utilized pricing. Although we intentionally structured this analysis to be simple to interpret and evaluate, we acknowledge that refining the methods could lead to more accurate strike probabilities. High-quality fisher data and rationales for staying in port would be the primary tool for reducing basis risk. Direct conversations or surveys with fishers could improve the estimated accuracy of losses and help identify additional threshold conditions that allow effort adaptations versus conditions that impede all potential fishing activity.</p>
<p>The result of the sensitivity test showed that the index varied strongly with thresholds of winds and waves. The thresholds are too strict thus labeling too many days non-fishable, making the index less practical. Contract triggers become weaker when very loose thresholds classify all days as fishable. The 8.5 m/s wind speed and 1.75m wave height value were selected to avoid extremes. It creates about 206.95 fishable days each year and has enough annual variation for pricing. Recent studies connecting weather thresholds and sea-state limits to marine access and operational downtime are consistent with this outcome. As per research, what is selected as threshold must depict actual working conditions, and not just the meteorological variation <span class="citation" data-cites="chittethramachandran2022 costas2023 karathanasi2022">(<a href="capstone.html#ref-chittethramachandran2022" role="doc-biblioref">Chitteth Ramachandran et al. 2022</a>; <a href="capstone.html#ref-costas2023" role="doc-biblioref">Costas et al. 2023</a>; <a href="capstone.html#ref-karathanasi2022" role="doc-biblioref">Karathanasi, Soukissian, and Hayes 2022</a>)</span>. This threshold strikes a nice balance, as demonstrated in our study. It still preserves commercial meaning and reflects real fishing conditions.</p>
<p>The pricing results also strengthen the structure of contracts. The regular fishability likelihoods follow a clear seasonal pattern, so the risk does not remain constant throughout the year. The observed pattern is a strong endorsement for the implementation of the Poisson-binomial model which makes the probabilities daily contract period-varying. The analysis of strikes shows practically no protection from low strikes, i.e.&nbsp;strikes from 80% to 87%, which is hardly that the trigger will activate. On the other hand, 93% to 95% strikes lead to the tanks producing a more active hedge with increased trigger probabilities and higher premiums. The evidence presented here is consistent with other studies on parametric insurance which find significant dependence of contract performance on trigger design and threshold placement which is typically at the core of the loss distribution <span class="citation" data-cites="larsson2023 xu2008">(<a href="capstone.html#ref-larsson2023" role="doc-biblioref">Larsson 2023</a>; <a href="capstone.html#ref-xu2008" role="doc-biblioref">Xu, Odening, and Musshoff 2008</a>)</span>. The data indicates that the upper strike range offers protection that is the most useful for fishers that want coverage during moderately adverse years, as opposed to only extreme years.</p>
<p>Currently, we still have limited information that we can use to independently determine fishable days. Although we did not consider that day-to-day business data would be required, information related to costs, revenue, and rationale for non-fished days would be critical to improve weather derivative pricing. Ideally, the benefits associated with rapid payments under a straightforward parametric insurance framework could serve as motivation for improving the quantity and quality of self-reported fisher activity. By establishing a transparent parametric framework, we were able to develop a user interface dashboard to communicate the weather derivative pricing over a range of strike percentages and different wind and wave threshold scenarios. By maintaining and improving this interactive dashboard, fishers would be able to customize the conditions to meet personal needs and preferences related to risk tolerance and budget. Ideally, creating a positive feedback loop of improved reporting, leading to more accurate thresholds, thereby reducing basis risk and making the insurance more affordable.</p>
</section>
<section id="conclusion" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">2.5</span> Conclusion</h2>
<p>This study proposes the fishable-day index for developing parametric insurance contracts for fishers. The procedure creates a daily index based on wind speed and wave height. It then estimates day-specific probabilities and applies to a Poisson-binomial model for seasonality. The findings indicate that selection of thresholds strongly governs index behavior. Highly restrictive parameters significantly decrease fishing days. Loosening limitations removes risk. The chosen thresholds of 8.5 m/s for wind and 1.75 m for wave height create a balanced set of criteria. It generates approximately 207 fishable days annually and sustains enough variance for pricing. The validation confirms that fishable days correspond with a peak fishing activity, thus justifying the practical relevance of the index. The seasonal probability pattern bolsters the choice of model since it shows real changes in fishing conditions during the year, allowing us to avoid an assumption of constant risk. The pricing results have important economic consequences. Strike levels that are too low mean almost zero trigger probability, which also does not offer much protection. Increasing the strike levels increases the chances of triggering and the premium. The range from 93% to 95% offers the most suitable balance of cost and coverage. The contract can respond to conditions that are only moderate or worse rather than only extreme events. The convex price pattern indicates that pricing is driven more by trigger probability than by payout size. The paper also identifies major limitations. Operational costs, reinsurance, and market risk loading are not included. It is also dependent on limited data of fishing activity that may mask true behavior because of reporting limitations. In the future, we must improve the quality of data, including fisher feedback, and further refine the threshold conditions. Broadening the framework to other regions or sectors would allow risk pooling. The research provides a well-defined and pragmatic framework for constructing a weather-based insurance instrument beneficial to fishers under uncertain conditions of the sea.</p>
</section>
<section id="references" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="references"><span class="header-section-number">2.6</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-alaton2002" class="csl-entry" role="listitem">
Alaton, Peter, Boualem Djehiche, and David Stillberger. 2002. <span>“On
Modelling and Pricing Weather Derivatives.”</span> <em>Applied
Mathematical Finance</em> 9 (1): 1–20. <a href="https://doi.org/10.1080/13504860210132897">https://doi.org/10.1080/13504860210132897</a>.
</div>
<div id="ref-bems2021" class="csl-entry" role="listitem">
Bemš, Július, and Caner Aydin. 2021. <span>“Introduction to Weather
Derivatives.”</span> <em>WIREs Energy and Environment</em> 11 (3). <a href="https://doi.org/10.1002/wene.426">https://doi.org/10.1002/wene.426</a>.
</div>
<div id="ref-biscarri2018" class="csl-entry" role="listitem">
Biscarri, William, Sihai Dave Zhao, and Robert J. Brunner. 2018.
<span>“A Simple and Fast Method for Computing the Poisson Binomial
Distribution Function.”</span> <em>Computational Statistics &amp; Data
Analysis</em> 122 (June): 92–100. <a href="https://doi.org/10.1016/j.csda.2018.01.007">https://doi.org/10.1016/j.csda.2018.01.007</a>.
</div>
<div id="ref-bressan2021" class="csl-entry" role="listitem">
Bressan, Giacomo Maria, and Silvia Romagnoli. 2021. <span>“Climate Risks
and Weather Derivatives: A Copula-Based Pricing Model.”</span>
<em>Journal of Financial Stability</em> 54 (June): 100877. <a href="https://doi.org/10.1016/j.jfs.2021.100877">https://doi.org/10.1016/j.jfs.2021.100877</a>.
</div>
<div id="ref-cao2004" class="csl-entry" role="listitem">
Cao, Melanie, and Jason Wei. 2004. <span>“Weather Derivatives Valuation
and Market Price of Weather Risk.”</span> <em>Journal of Futures
Markets</em> 24 (11): 1065–89. <a href="https://doi.org/10.1002/fut.20122">https://doi.org/10.1002/fut.20122</a>.
</div>
<div id="ref-chen1997" class="csl-entry" role="listitem">
Chen, Sean X., and Jun S. Liu. 1997. <span>“Statistical Applications of
the Poisson-Binomial and Conditional Bernoulli Distributions.”</span>
<em>Statistica Sinica</em> 7 (4): 875–92. <a href="https://www.jstor.org/stable/24306160">https://www.jstor.org/stable/24306160</a>.
</div>
<div id="ref-chittethramachandran2022" class="csl-entry" role="listitem">
Chitteth Ramachandran, Rahul, Cian Desmond, Frances Judge, Jorrit-Jan
Serraris, and Jimmy Murphy. 2022. <span>“Floating Wind Turbines: Marine
Operations Challenges and Opportunities.”</span> <em>Wind Energy
Science</em> 7 (2): 903–24. <a href="https://doi.org/10.5194/wes-7-903-2022">https://doi.org/10.5194/wes-7-903-2022</a>.
</div>
<div id="ref-costas2023" class="csl-entry" role="listitem">
Costas, Raquel, Humberto Carro, Andrés Figuero, Enrique Peña, and José
Sande. 2023. <span>“A Decision-Making Tool for Port Operations Based on
Downtime Risk and Met-Ocean Conditions Including Infragravity Wave
Forecast.”</span> <em>Journal of Marine Science and Engineering</em> 11
(3): 536. <a href="https://doi.org/10.3390/jmse11030536">https://doi.org/10.3390/jmse11030536</a>.
</div>
<div id="ref-fernandez2010" class="csl-entry" role="listitem">
Fernandez, Manuel, and Stuart Williams. 2010. <span>“Closed-Form
Expression for the Poisson-Binomial Probability Density
Function.”</span> <em>IEEE Transactions on Aerospace and Electronic
Systems</em> 46 (2): 803–17. <a href="https://doi.org/10.1109/taes.2010.5461658">https://doi.org/10.1109/taes.2010.5461658</a>.
</div>
<div id="ref-hersbach2020" class="csl-entry" role="listitem">
Hersbach, Hans, Bill Bell, Paul Berrisford, Shoji Hirahara, András
Horányi, Joaquín Muñoz-Sabater, Julien Nicolas, et al. 2020. <span>“The
ERA5 Global Reanalysis.”</span> <em>Quarterly Journal of the Royal
Meteorological Society</em> 146 (730): 1999–2049. <a href="https://doi.org/10.1002/qj.3803">https://doi.org/10.1002/qj.3803</a>.
</div>
<div id="ref-hong2013" class="csl-entry" role="listitem">
Hong, Yili. 2013. <span>“On Computing the Distribution Function for the
Poisson Binomial Distribution.”</span> <em>Computational Statistics
&amp; Data Analysis</em> 59 (March): 41–51. <a href="https://doi.org/10.1016/j.csda.2012.10.006">https://doi.org/10.1016/j.csda.2012.10.006</a>.
</div>
<div id="ref-jewson2005" class="csl-entry" role="listitem">
Jewson, Stephen, Anders Brix, and Christine Ziehmann. 2005.
<span>“Weather Derivative Valuation,”</span> March. <a href="https://doi.org/10.1017/cbo9780511493348">https://doi.org/10.1017/cbo9780511493348</a>.
</div>
<div id="ref-karathanasi2022" class="csl-entry" role="listitem">
Karathanasi, Flora E., Takvor H. Soukissian, and Daniel R. Hayes. 2022.
<span>“Wave Analysis for Offshore Aquaculture Projects: A Case Study for
the Eastern Mediterranean Sea.”</span> <em>Climate</em> 10 (1): 2. <a href="https://doi.org/10.3390/cli10010002">https://doi.org/10.3390/cli10010002</a>.
</div>
<div id="ref-kath2018" class="csl-entry" role="listitem">
Kath, Jarrod, Shahbaz Mushtaq, Ross Henry, Adewuyi Adeyinka, and Roger
Stone. 2018. <span>“Index Insurance Benefits Agricultural Producers
Exposed to Excessive Rainfall Risk.”</span> <em>Weather and Climate
Extremes</em> 22 (December): 1–9. <a href="https://doi.org/10.1016/j.wace.2018.10.003">https://doi.org/10.1016/j.wace.2018.10.003</a>.
</div>
<div id="ref-larsson2023" class="csl-entry" role="listitem">
Larsson, Karl. 2023. <span>“Parametric Heat Wave Insurance.”</span>
<em>Journal of Commodity Markets</em> 31 (September): 100345. <a href="https://doi.org/10.1016/j.jcomm.2023.100345">https://doi.org/10.1016/j.jcomm.2023.100345</a>.
</div>
<div id="ref-richards2004" class="csl-entry" role="listitem">
Richards, Timothy J., Mark R. Manfredo, and Dwight R. Sanders. 2004.
<span>“Pricing Weather Derivatives.”</span> <em>American Journal of
Agricultural Economics</em> 86 (4): 1005–17. <a href="https://doi.org/10.1111/j.0002-9092.2004.00649.x">https://doi.org/10.1111/j.0002-9092.2004.00649.x</a>.
</div>
<div id="ref-skees2008" class="csl-entry" role="listitem">
Skees, Jerry R. 2008. <span>“Innovations in Index Insurance for the Poor
in Lower Income Countries.”</span> <em>Agricultural and Resource
Economics Review</em> 37 (1): 1–15. <a href="https://doi.org/10.1017/s1068280500002094">https://doi.org/10.1017/s1068280500002094</a>.
</div>
<div id="ref-caribbea" class="csl-entry" role="listitem">
Southeast Fisheries Science Center. 2026. <span>“Caribbean ST Croix
Logbook Survey (Vessels).”</span> <a href="https://www.fisheries.noaa.gov/inport/item/30423">https://www.fisheries.noaa.gov/inport/item/30423</a>.
</div>
<div id="ref-taib2012" class="csl-entry" role="listitem">
Taib, Che Mohd Imran Che, and Fred Espen Benth. 2012. <span>“Pricing of
Temperature Index Insurance.”</span> <em>Review of Development
Finance</em> 2 (1): 22–31. <a href="https://doi.org/10.1016/j.rdf.2012.01.004">https://doi.org/10.1016/j.rdf.2012.01.004</a>.
</div>
<div id="ref-worldbank2011" class="csl-entry" role="listitem">
World Bank. 2011. <span>“Weather Index Insurance for Agriculture:
Guidance for Development Practitioners.”</span> 50. Agriculture and
Rural Development Discussion Paper. Washington, DC: The World Bank. <a href="https://doi.org/10.1596/26889">https://doi.org/10.1596/26889</a>.
</div>
<div id="ref-worldbank2023" class="csl-entry" role="listitem">
———. 2023. <span>“Index-Based Weather Derivative: Product Note.”</span>
Washington, DC: World Bank. <a href="https://thedocs.worldbank.org/en/doc/29d15a97a9791b5e6cfac1c302d08f08-0340012023/original/product-note-index-based-weather-derivative.pdf">https://thedocs.worldbank.org/en/doc/29d15a97a9791b5e6cfac1c302d08f08-0340012023/original/product-note-index-based-weather-derivative.pdf</a>.
</div>
<div id="ref-xu2008" class="csl-entry" role="listitem">
Xu, Wei, Martin Odening, and Oliver Musshoff. 2008. <span>“Indifference
Pricing of Weather Derivatives.”</span> <em>American Journal of
Agricultural Economics</em> 90 (4): 979–93. <a href="https://doi.org/10.1111/j.1467-8276.2008.01154.x">https://doi.org/10.1111/j.1467-8276.2008.01154.x</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/adyadyan\.github\.io\/MAP-5629-Capstone\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/proposal.html" class="pagination-link" aria-label="Proposal">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Proposal</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/downloads.html" class="pagination-link" aria-label="Downloads">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Downloads</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/adyadyan/MAP-5629-Capstone/edit/main/chapters/capstone.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/adyadyan/MAP-5629-Capstone/blob/main/chapters/capstone.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/adyadyan/MAP-5629-Capstone/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>